services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=your-secure-secret-key
      - DATABASE_URL=postgresql://postgres:password@db:5432/contacts
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
      - ./ssl:/app/ssl:ro  # Mount SSL directory as read-only
    command: python app.py
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=contacts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: